/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import glbank.Client;

/**
 *
 * @author Joseph
 */
public class EditClientForm extends javax.swing.JFrame {
    
    private Client client;

    public EditClientForm(Client client) {
        initComponents();
        this.client = client;
        setInformationToEdit();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        txtEditClientPostcode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEditClientUsername = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEditClientPassword = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEditClientFirstName = new javax.swing.JTextField();
        txtEditClientLastName = new javax.swing.JTextField();
        txtEditClientDOB = new javax.swing.JTextField();
        txtEditClientEmail = new javax.swing.JTextField();
        btnEditClientCreate = new javax.swing.JButton();
        txtEditClientCity = new javax.swing.JTextField();
        btnEditClientCancel = new javax.swing.JButton();
        txtEditClientStreet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtEditClientHousenumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Username:");

        jLabel8.setText("Date of birth:");

        jLabel9.setText("City");

        txtEditClientPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditClientPasswordActionPerformed(evt);
            }
        });

        jLabel10.setText("Password:");

        btnEditClientCreate.setText("Edit");
        btnEditClientCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientCreateActionPerformed(evt);
            }
        });

        txtEditClientCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditClientCityActionPerformed(evt);
            }
        });

        btnEditClientCancel.setText("Cancel");
        btnEditClientCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditClientCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("First name:");

        jLabel2.setText("Last name:");

        jLabel3.setText("Email:");

        jLabel4.setText("Street: ");

        jLabel5.setText("Housenumber:");

        jLabel6.setText("Postcode:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEditClientCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditClientLastName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditClientFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditClientDOB, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditClientStreet, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditClientEmail)
                            .addComponent(txtEditClientHousenumber)
                            .addComponent(txtEditClientPostcode)
                            .addComponent(txtEditClientUsername)
                            .addComponent(txtEditClientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btnEditClientCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditClientCancel)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEditClientFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEditClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtEditClientDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEditClientEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtEditClientCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEditClientStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditClientHousenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditClientPostcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditClientUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditClientPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditClientCreate)
                    .addComponent(btnEditClientCancel))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEditClientPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditClientPasswordActionPerformed

    }//GEN-LAST:event_txtEditClientPasswordActionPerformed

    private void btnEditClientCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientCreateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditClientCreateActionPerformed

    private void txtEditClientCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditClientCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEditClientCityActionPerformed

    private void btnEditClientCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditClientCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnEditClientCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditClientCancel;
    private javax.swing.JButton btnEditClientCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEditClientCity;
    private javax.swing.JTextField txtEditClientDOB;
    private javax.swing.JTextField txtEditClientEmail;
    private javax.swing.JTextField txtEditClientFirstName;
    private javax.swing.JTextField txtEditClientHousenumber;
    private javax.swing.JTextField txtEditClientLastName;
    private javax.swing.JTextField txtEditClientPassword;
    private javax.swing.JTextField txtEditClientPostcode;
    private javax.swing.JTextField txtEditClientStreet;
    private javax.swing.JTextField txtEditClientUsername;
    // End of variables declaration//GEN-END:variables

    private void setInformationToEdit() {
        txtEditClientFirstName.setText(client.getFirstname());
        txtEditClientLastName.setText(client.getLastname());
        txtEditClientDOB.setText("" + client.getDob());
        txtEditClientEmail.setText(client.getEmail());
        txtEditClientCity.setText(client.getCity());
        txtEditClientStreet.setText(client.getStreet());
        txtEditClientHousenumber.setText("" + client.getHousenumber());
        txtEditClientPostcode.setText(client.getPostcode());
        txtEditClientUsername.setText(client.getUsername());
        txtEditClientPassword.setText(client.getPassword());
    }
}
