CREATE TABLE Clients (
	idc INTEGER AUTO_INCREMENT,
	firstname VARCHAR(20) NOT NULL,
	lastname VARCHAR(20) NOT NULL,
	disable CHAR(1) DEFAULT 'F',
	PRIMARY KEY (idc)
);

CREATE TABLE ClientDetails (
	idcd INTEGER AUTO_INCREMENT,
	idc INTEGER NOT NULL,
	street VARCHAR(20) NOT NULL,
	houseNumber INTEGER NOT NULL,
	postcode CHAR(5) NOT NULL,
	city VARCHAR(20) NOT NULL,
	dob DATE NOT NULL,
	email VARCHAR(30),
	PRIMARY KEY (idcd),
	FOREIGN KEY (idc)
		REFERENCES Clients (idc)
		ON DELETE CASCADE ON UPDATE RESTRICT
);

CREATE TABLE LoginClient (
	idlc INTEGER AUTO_INCREMENT,
	idc INTEGER NOT NULL,
	username VARCHAR(20) NOT NULL,
	password VARCHAR(20) NOT NULL,
	blocked CHAR(1) DEFAULT 'F',
	PRIMARY KEY (idlc),
	FOREIGN KEY (idc)
		REFERENCES Clients (idc)
		ON DELETE CASCADE ON UPDATE RESTRICT
);