INSERT INTO Clients VALUES(1,'Jozef','Balint','F');
INSERT INTO Clients VALUES(2,'Martin','Molnar','F');
INSERT INTO Clients VALUES(3,'Tana','Pauhoffova','F');
INSERT INTO ClientDetails VALUES(1,1,'Lomnicka',20,'08005','Presov','1994-03-21','jozef@gmail.com');
INSERT INTO ClientDetails VALUES(2,2,'Kosicka',2,'04011','Bardejov','1998-05-15','martin@centrum.sk');
INSERT INTO ClientDetails VALUES(3,3,'Presovska',33,'08001','Kosice','1990-11-01','tana.pau@hotmail.com');
INSERT INTO LoginClient VALUES(1,1,'balint','balint','F');
INSERT INTO LoginClient VALUES(2,2,'molnar','molnar','F');
INSERT INTO LoginClient VALUES(3,3,'pauhoff','pauhoff','F');