/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.panels.accountPanels;

import database.ConnectionProvider;
import javax.swing.JOptionPane;

/**
 *
 * @author Joseph
 */
public class ChangePINForm extends javax.swing.JFrame {

    private int idCard;
    /**
     * Creates new form ChangePINForm
     */
    public ChangePINForm(int idCard) {
        initComponents();
        setLocationRelativeTo(null);
        this.idCard = idCard;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtChangePINNewPIN = new javax.swing.JTextField();
        txtChangePINNewPINRepeat = new javax.swing.JTextField();
        btnChangePINCancel = new javax.swing.JButton();
        btnChangePINOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("New PIN: ");

        jLabel2.setText("Repeat new PIN: ");

        btnChangePINCancel.setText("Cancel");
        btnChangePINCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePINCancelActionPerformed(evt);
            }
        });

        btnChangePINOK.setText("OK");
        btnChangePINOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePINOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(btnChangePINOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtChangePINNewPIN)
                        .addComponent(txtChangePINNewPINRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnChangePINCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtChangePINNewPIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtChangePINNewPINRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChangePINCancel)
                    .addComponent(btnChangePINOK))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChangePINCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePINCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnChangePINCancelActionPerformed

    private void btnChangePINOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePINOKActionPerformed
        String newPIN = txtChangePINNewPIN.getText();
        String newPIN2 = txtChangePINNewPINRepeat.getText();
        if(validatePIN(newPIN, newPIN2)){
            changePIN(newPIN);
            JOptionPane.showMessageDialog(null, "PIN succesfully changed.");
            this.dispose(); 
        }else{
            JOptionPane.showMessageDialog(null, "An error occured whle changing PIN.");
        }       
    }//GEN-LAST:event_btnChangePINOKActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePINCancel;
    private javax.swing.JButton btnChangePINOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtChangePINNewPIN;
    private javax.swing.JTextField txtChangePINNewPINRepeat;
    // End of variables declaration//GEN-END:variables


    private boolean validatePIN(String newPIN, String newPIN2){
        newPIN = txtChangePINNewPIN.getText();
        newPIN2 = txtChangePINNewPINRepeat.getText();
        
        if(isInt(newPIN) && newPIN.length() == 4 && newPIN.equals(newPIN2)){
            return true;            
        }else{
            JOptionPane.showMessageDialog(btnChangePINOK.getRootPane(), "PINs don't match!");
            return false;
        }
    }
    
    private void changePIN(String newPIN){
        ConnectionProvider conn = new ConnectionProvider();
        int pin = parseStringToInt(newPIN);
        conn.changePIN(pin, idCard);
    }

    private boolean isInt(String str){
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(btnChangePINOK.getRootPane(), "PIN can only be a number exactly 4 digits long!");
            return false;
        }
    }
    
    private int parseStringToInt(String value){
        int intValue = Integer.parseInt(value);
        return intValue;
    }
    
    


}

